Repository Faiza-Maghrabi/FoxPuzzle, pull requests merged in 2024-10, with the labels that each got.

#27 Feat/food items
  Assets/Prefabs.meta
  Assets/Prefabs/FoodMeshes.meta
  Assets/Prefabs/FoodMeshes/pizza.fbx
  Assets/Prefabs/FoodMeshes/pizza.fbx.meta
  Assets/Prefabs/FoodPrefab.prefab
  Assets/Prefabs/FoodPrefab.prefab.meta
  Assets/Prefabs/Player.prefab
  Assets/Prefabs/Player.prefab.meta
  Assets/Scenes/FaizaTestScene.unity
  Assets/Scenes/FaizaTestScene.unity.meta
  Assets/Scripts/Food.meta
  Assets/Scripts/Food/FoodList.json
  Assets/Scripts/Food/FoodList.json.meta
  Assets/Scripts/Food/FoodScript.cs
  Assets/Scripts/Food/FoodScript.cs.meta
  Assets/Scripts/PlayerController.cs
  ProjectSettings/TagManager.asset
Labels: Gameplay, Aesthetics, Non-Playable Features

#29 Feat: Added jump functionality :)
  Assets/Scenes/HazalTestingScene.unity
  Assets/Scripts/PlayerController.cs
Labels: Controls, Gameplay

#36 Feat/inventory system and selecting items
  Assets/Prefabs/HealthAttribute.prefab
  Assets/Prefabs/Inventory.prefab
  Assets/Prefabs/Inventory.prefab.meta
  Assets/Prefabs/InventoryIcon.prefab
  Assets/Prefabs/InventoryIcon.prefab.meta
  Assets/Prefabs/Player.prefab
  Assets/Prefabs/PlayerAndCam.prefab
  Assets/Prefabs/PlayerCanvas.prefab
  Assets/Prefabs/PlayerCanvas.prefab.meta
  Assets/Scenes/HazalTestingScene.unity
  Assets/Scripts/DontDestroy.cs
  Assets/Scripts/DontDestroy.cs.meta
  Assets/Scripts/Food/FoodList.json
  Assets/Scripts/Food/FoodScript.cs
  Assets/Scripts/HealthBar.cs
  Assets/Scripts/Inventory.cs
  Assets/Scripts/Inventory.cs.meta
  Assets/Scripts/ItemSlot.cs
  Assets/Scripts/ItemSlot.cs.meta
  Assets/Scripts/PlayerController.cs
  ProjectSettings/InputManager.asset
Labels: Gameplay, Aesthetics

#38 Feat/upgrading open house
  Assets/Scenes/FaizaTestScene.unity
  Assets/Scenes/OpenHouse/New Terrain.asset
  Assets/Scenes/OpenHouse/OpenHouseScene.unity
Labels: Environment, Gameplay

#40 Feat/game loop and end criteria
  Assets/CardBoard.mat
  Assets/CardBoard.mat.meta
  Assets/Orange.mat
  Assets/Orange.mat.meta
  Assets/Prefabs/Fox Den.prefab
  Assets/Prefabs/Fox Den.prefab.meta
  Assets/Prefabs/Player.prefab
  Assets/Scenes/EndScene.unity
  Assets/Scenes/EndScene.unity.meta
  Assets/Scripts/EndScene.cs
  Assets/Scripts/EndScene.cs.meta
  Assets/Scripts/PlayerController.cs
Labels: Gameplay, Aesthetics, Non-Playable Features

#31 Main menu
  Assets/Images.meta
  Assets/Materials.meta
  Assets/Materials/Blue.mat
  Assets/Materials/Blue.mat.meta
  Assets/Materials/Brown.mat
  Assets/Materials/Brown.mat.meta
  Assets/Materials/Grass.mat
  Assets/Materials/Grass.mat.meta
  Assets/Materials/Green.mat
  Assets/Materials/Green.mat.meta
  Assets/Materials/Grey.mat
  Assets/Materials/Grey.mat.meta
  Assets/Materials/Red.mat
  Assets/Materials/Red.mat.meta
  Assets/Materials/Snow.mat
  Assets/Materials/Snow.mat.meta
  Assets/Materials/Yellow.mat
  Assets/Materials/Yellow.mat.meta
  Assets/New Terrain.asset
  Assets/New Terrain.asset.meta
  Assets/Scenes/MainMenu.unity
  Assets/Scenes/MainMenu.unity.meta
  Assets/Scenes/OpenScene.unity
  Assets/Scenes/OpenScene.unity.meta
  Assets/Scripts/LoadHouse1.cs
  Assets/Scripts/LoadHouse1.cs.meta
  Assets/Scripts/StartGame.cs
  Assets/Scripts/StartGame.cs.meta
  Assets/TextMesh Pro/Resources/Fonts & Materials/LiberationSans SDF.asset
  Assets/Tree.prefab
  Assets/Tree.prefab.meta
  Assets/Tree_Textures.meta
  Assets/Tree_Textures/diffuse.png
  Assets/Tree_Textures/diffuse.png.meta
  Assets/Tree_Textures/normal_specular.png
  Assets/Tree_Textures/normal_specular.png.meta
  Assets/Tree_Textures/shadow.png
  Assets/Tree_Textures/shadow.png.meta
  Assets/Tree_Textures/translucency_gloss.png
  Assets/Tree_Textures/translucency_gloss.png.meta
  Packages/manifest.json
  Packages/packages-lock.json
  ProjectSettings/EditorBuildSettings.asset
Labels: Non-Playable Features
